<?php

namespace Epsi\FirstBundle\Repository;

/**
 * ComporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComporteRepository extends \Doctrine\ORM\EntityRepository
{
}
