<?php

namespace Epsi\FirstBundle\Repository;

/**
 * motRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motRepository extends \Doctrine\ORM\EntityRepository
{
}
