<?php

namespace Epsi\FirstBundle\Repository;

/**
 * testRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class testRepository extends \Doctrine\ORM\EntityRepository
{
        public function deleteTest($id) {
        $r = $this->_em
                -> createQueryBuilder()
                ->delete($this->_entityName,'t')
                ->where('t.id=:test_id')
                ->setParameter('test_id',$id)
                ->getQuery();
        return 1 === $r->getScalarResult();
    }
    public function findAllModif(): array {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT test.id,test.Libelle as libelle,test.niveau, theme.libelle as theme '
                . 'from test,theme '
                . 'where test.theme_id = theme.id';
        $stmt= $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
        
    }
    
    public function findMotByTest($id) {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT mot.Libelle from mot INNER JOIN comporte ON mot.id = comporte.mot_id INNER JOIN liste_mot ON comporte.liste_mot_id=liste_mot.id INNER JOIN theme ON liste_mot.theme_id=theme.id INNER JOIN test ON theme.id = test.theme_id WHERE test.theme_id ='.$id;
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    
        public function findMotAnglaisByTest($id) {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT mot.LibelleAnglais from mot INNER JOIN comporte ON mot.id = comporte.mot_id INNER JOIN liste_mot ON comporte.liste_mot_id=liste_mot.id INNER JOIN theme ON liste_mot.theme_id=theme.id INNER JOIN test ON theme.id = test.theme_id WHERE test.theme_id ='.$id;
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
