<?php

namespace Epsi\FirstBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteTheme($id) {
        $r = $this->_em
                -> createQueryBuilder()
                ->delete($this->_entityName,'t')
                ->where('t.id=:theme_id')
                ->setParameter('theme_id',$id)
                ->getQuery();
        return 1 === $r->getScalarResult();
    }
    public function selectTestByTheme($id) {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'select test.id, test.Libelle, test.niveau, ( select theme.libelle from theme where id ='.$id.') as ThemeLibelle from test INNER JOIN theme ON theme.id=test.id where theme_id='.$id;
        $stmt= $conn->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
