<?php

namespace Epsi\FirstBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteUtilisateur($id)
    {
        $r = $this->_em
            ->createQueryBuilder()
            ->delete($this->_entityName, 'c')
            ->where('c.id = :utilisateur_id')
            ->setParameter('utilisateur_id', $id)
            ->getQuery()
        ;
        return 1 === $r->getScalarResult();
    }
}
