# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      Epsi\FirstBundle\Entity\Utilisateur: sha512
        
    role_hierarchy:
       ROLE_ADMIN: ROLE_USER
       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       main:
        entity:
          class: Epsi\FirstBundle\Entity\Utilisateur
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false

        main:
         pattern: ^/
         anonymous: true
         provider: main
         form_login:
           login_path: login
           check_path: login_check
         logout:
           path: logout
           target: /
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
            
    access_control:
    - { path:^/admin, roles:ROLE_ADMIN }
    - { path:^/member, roles:ROLE_USER }